[font]
size = 15

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[scrolling]
history = 10000

[window]
dynamic_padding = true
startup_mode = "Windowed"
opacity = 0.8
blur = true
option_as_alt = "Both"

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
