[font]
size = 15

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[scrolling]
history = 10000

[terminal.shell]
program = "/bin/zsh"
args = [
    "-l",
    "-c",
    "tmux new-session -A -s main",
]

[window]
dynamic_padding = true
startup_mode = "Fullscreen"
option_as_alt = "OnlyLeft"

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
